# ============================================
# General Settings
# ============================================
set -g base-index 1
setw -g pane-base-index 1
set -g mouse on
set -g history-limit 10000
set -sg escape-time 10
set -g default-terminal "screen-256color"
setw -g mode-keys vi

# Set plugin installation directory
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.config/tmux/plugins/'
